"""Local AI Assistant Service — Context Serialization, Natural Language DAW Command Parser & Plan Generator."""

import re
from typing import Dict, Any, List, Optional, Tuple
from pydantic import BaseModel, Field

from backend.app.schemas.project import Project
from backend.app.services.project_service import ProjectService
from backend.app.logging_config import logger


class AIOperation(BaseModel):
    """Represents a single atomic DAW command within an AI proposal."""
    op: str  # 'set_volume', 'set_pan', 'mute_track', 'unmute_track', 'solo_track', 'unsolo_track', 'add_effect', 'set_tempo', 'split_clip', 'separate_stems', 'apply_spatial'
    track_id: Optional[str] = None
    track_name: Optional[str] = None
    clip_id: Optional[str] = None
    description: str
    params: Dict[str, Any] = Field(default_factory=dict)
    current_value: Optional[Any] = None
    target_value: Optional[Any] = None


class AIOperationPlan(BaseModel):
    """Structured proposal generated by AI for user review and execution."""
    prompt: str
    summary: str
    confidence: float = 1.0
    operations: List[AIOperation] = Field(default_factory=list)


class AIService:
    """Local AI DAW Assistant engine supporting offline intent recognition, fuzzy entity matching, and safety validation."""

    @classmethod
    def get_project_context(cls, project: Project) -> Dict[str, Any]:
        """Serialize project state into structured context for AI reasoning."""
        tracks_summary = []
        total_clips = 0

        for t in project.tracks:
            clip_count = len(t.clips)
            total_clips += clip_count
            tracks_summary.append({
                "id": t.id,
                "name": t.name,
                "volume_db": t.volume,
                "pan": t.pan,
                "is_muted": t.is_muted,
                "is_soloed": t.is_soloed,
                "effects": [e.type for e in t.effects if not e.is_bypassed],
                "clip_count": clip_count,
            })

        return {
            "project_id": project.id,
            "project_name": project.name,
            "tempo": project.tempo,
            "sample_rate": project.sample_rate,
            "total_tracks": len(project.tracks),
            "total_clips": total_clips,
            "tracks": tracks_summary,
        }

    @classmethod
    def generate_suggestions(cls, project: Project) -> List[Dict[str, str]]:
        """Generate context-aware prompt chips based on active project state."""
        suggestions = []
        tracks = project.tracks

        has_vocals = any("vocal" in t.name.lower() or "vox" in t.name.lower() for t in tracks)
        has_drums = any("drum" in t.name.lower() or "beat" in t.name.lower() for t in tracks)

        if has_drums:
            suggestions.append({
                "title": "Lower Drums",
                "prompt": "Lower drums volume by 3 dB",
                "category": "Mixing",
            })
        if has_vocals:
            suggestions.append({
                "title": "Vocal Reverb",
                "prompt": "Add Reverb to vocals with 25% wet mix",
                "category": "Effects",
            })
        if not has_drums and not has_vocals and tracks:
            suggestions.append({
                "title": "Separate Stems",
                "prompt": "Separate audio into 4 stems on GPU",
                "category": "AI Separation",
            })

        suggestions.append({
            "title": "8D Binaural",
            "prompt": "Enable 8D audio on master with figure-8 orbit",
            "category": "Spatial",
        })

        suggestions.append({
            "title": "Tempo Change",
            "prompt": f"Set tempo to {round(project.tempo + 5, 1)} BPM",
            "category": "Arrangement",
        })

        return suggestions[:4]

    @classmethod
    def resolve_track(cls, text: str, tracks: List[Any]) -> Optional[Any]:
        """Fuzzy match track name or number mentioned in natural text."""
        text_lower = text.lower()

        # 1. Exact or partial track name match
        for t in tracks:
            t_name = t.name.lower()
            if t_name in text_lower or (len(t_name) >= 3 and t_name in text_lower):
                return t

        # 2. Numbered track ("track 1", "track 2", "first track")
        match_num = re.search(r"track\s*(\d+)", text_lower)
        if match_num:
            idx = int(match_num.group(1)) - 1
            if 0 <= idx < len(tracks):
                return tracks[idx]

        if "first track" in text_lower and len(tracks) > 0:
            return tracks[0]
        if "second track" in text_lower and len(tracks) > 1:
            return tracks[1]
        if "third track" in text_lower and len(tracks) > 2:
            return tracks[2]

        # 3. Keyword semantic synonyms
        synonyms = {
            "drums": ["drum", "beat", "kick", "snare", "percussion", "rhythm"],
            "vocals": ["vocal", "vox", "voice", "singer", "singing", "acapella"],
            "bass": ["bass", "sub", "808", "bassline", "low end"],
            "guitar": ["guitar", "gtr", "acoustic", "electric"],
            "synth": ["synth", "lead", "melody", "keys", "piano", "pad"],
        }
        for t in tracks:
            t_name = t.name.lower()
            for category, keywords in synonyms.items():
                if any(kw in t_name for kw in keywords):
                    if any(kw in text_lower for kw in keywords):
                        return t

        return None

    @classmethod
    def _parse_single_clause(cls, clause: str, project: Project) -> List[AIOperation]:
        """Parse an individual sub-clause into atomic AIOperation items."""
        p_lower = clause.strip().lower()
        if not p_lower:
            return []

        tracks = project.tracks
        ops: List[AIOperation] = []

        # 1. STEM SEPARATION
        if any(w in p_lower for w in ["separate stem", "split stem", "extract stem", "demucs"]):
            ops.append(AIOperation(
                op="separate_stems",
                description="Trigger Demucs 4-stem GPU separation on active audio track",
                params={"model": "htdemucs", "shifts": 1},
            ))
            return ops

        # 2. 8D SPATIAL AUDIO
        if any(w in p_lower for w in ["8d", "binaural", "spatial", "orbit"]):
            traj = "figure8" if ("figure" in p_lower or "8" in p_lower) else "circular"
            if "pendulum" in p_lower or "sweep" in p_lower:
                traj = "pendulum"
            
            speed = 7.5
            speed_match = re.search(r"(\d+(?:\.\d+)?)\s*(?:s|sec|seconds)", p_lower)
            if speed_match:
                speed = float(speed_match.group(1))

            ops.append(AIOperation(
                op="apply_spatial",
                description=f"Enable 8D Binaural Spatial Audio with {traj} trajectory ({speed}s period)",
                params={"enabled": True, "trajectory": traj, "speed": speed, "depth": 0.95},
                current_value="Bypassed",
                target_value=f"Active ({traj.capitalize()})",
            ))
            return ops

        # 3. TEMPO
        tempo_match = re.search(r"(?:tempo|bpm)\s*(?:to|=)?\s*(\d+(?:\.\d+)?)", p_lower)
        if not tempo_match and ("slow down" in p_lower or "speed up" in p_lower):
            delta = 10 if "speed up" in p_lower else -10
            new_tempo = max(30.0, min(300.0, project.tempo + delta))
            ops.append(AIOperation(
                op="set_tempo",
                description=f"Change project tempo to {new_tempo} BPM",
                params={"tempo": new_tempo},
                current_value=f"{project.tempo} BPM",
                target_value=f"{new_tempo} BPM",
            ))
            return ops
        elif tempo_match:
            new_tempo = max(30.0, min(300.0, float(tempo_match.group(1))))
            ops.append(AIOperation(
                op="set_tempo",
                description=f"Change project tempo to {new_tempo} BPM",
                params={"tempo": new_tempo},
                current_value=f"{project.tempo} BPM",
                target_value=f"{new_tempo} BPM",
            ))
            return ops

        # 4. TRACK IDENTIFICATION
        target_track = cls.resolve_track(p_lower, tracks)

        # ADD EFFECT
        effect_keywords = {
            "reverb": "reverb",
            "delay": "delay",
            "tape saturation": "tape_saturation",
            "tape": "tape_saturation",
            "saturation": "tape_saturation",
            "tube overdrive": "tube_overdrive",
            "overdrive": "tube_overdrive",
            "tube": "tube_overdrive",
            "chorus": "chorus",
            "stereo width": "stereo_width",
            "widener": "stereo_width",
            "compressor": "compressor",
            "limiter": "limiter",
            "eq": "equalizer",
        }
        found_effect = None
        for kw, eff_type in effect_keywords.items():
            if kw in p_lower:
                found_effect = eff_type
                break

        if found_effect:
            wet_match = re.search(r"(\d+)\s*%\s*(?:wet|mix)?", p_lower)
            wet_val = (float(wet_match.group(1)) / 100.0) if wet_match else 0.35
            eff_params = {"mix": wet_val}
            eff_track = target_track or (tracks[0] if tracks else None)
            if eff_track:
                ops.append(AIOperation(
                    op="add_effect",
                    track_id=eff_track.id,
                    track_name=eff_track.name,
                    description=f"Insert {found_effect.replace('_', ' ').title()} onto '{eff_track.name}' ({int(wet_val*100)}% wet)",
                    params={"track_id": eff_track.id, "type": found_effect, "params": eff_params},
                    current_value="None",
                    target_value=f"{found_effect} ({int(wet_val*100)}% mix)",
                ))
            return ops

        # VOLUME / GAIN
        vol_db_match = re.search(r"([+-]?\d+(?:\.\d+)?)\s*(?:db|decibel)", p_lower)
        is_vol_change = any(k in p_lower for k in ["volume", "gain", "louder", "quieter", "lower", "boost", "cut", "reduce", "increase", "db"])
        if is_vol_change and target_track:
            curr_vol = target_track.volume
            new_vol = curr_vol

            if vol_db_match:
                val = float(vol_db_match.group(1))
                if any(w in p_lower for w in ["lower", "reduce", "cut", "decrease", "down"]):
                    new_vol = curr_vol - abs(val)
                elif any(w in p_lower for w in ["increase", "boost", "raise", "up"]):
                    new_vol = curr_vol + abs(val)
                elif "by" in p_lower:
                    new_vol = curr_vol + val
                else:
                    new_vol = val
            elif "lower" in p_lower or "quieter" in p_lower:
                new_vol = curr_vol - 3.0
            elif "louder" in p_lower or "boost" in p_lower:
                new_vol = curr_vol + 3.0

            new_vol = max(-60.0, min(12.0, round(new_vol, 1)))
            ops.append(AIOperation(
                op="set_volume",
                track_id=target_track.id,
                track_name=target_track.name,
                description=f"Set volume of '{target_track.name}' to {new_vol:+0.1f} dB",
                params={"track_id": target_track.id, "volume": new_vol},
                current_value=f"{curr_vol:+0.1f} dB",
                target_value=f"{new_vol:+0.1f} dB",
            ))
            return ops

        # MUTE / UNMUTE
        if any(w in p_lower for w in ["mute", "silence", "unmute"]):
            mute_target = not ("unmute" in p_lower)
            if target_track:
                ops.append(AIOperation(
                    op="mute_track" if mute_target else "unmute_track",
                    track_id=target_track.id,
                    track_name=target_track.name,
                    description=f"{'Mute' if mute_target else 'Unmute'} track '{target_track.name}'",
                    params={"track_id": target_track.id, "is_muted": mute_target},
                    current_value="Muted" if target_track.is_muted else "Unmuted",
                    target_value="Muted" if mute_target else "Unmuted",
                ))
            return ops

        # SOLO / UNSOLO
        if "solo" in p_lower:
            solo_target = not ("unsolo" in p_lower)
            if target_track:
                ops.append(AIOperation(
                    op="solo_track" if solo_target else "unsolo_track",
                    track_id=target_track.id,
                    track_name=target_track.name,
                    description=f"{'Solo' if solo_target else 'Unsolo'} track '{target_track.name}'",
                    params={"track_id": target_track.id, "is_soloed": solo_target},
                    current_value="Soloed" if target_track.is_soloed else "Normal",
                    target_value="Soloed" if solo_target else "Normal",
                ))
            return ops

        # PAN
        if "pan" in p_lower and target_track:
            new_pan = target_track.pan
            if "left" in p_lower:
                pct = re.search(r"(\d+)\s*%", p_lower)
                val = (float(pct.group(1)) / 100.0) if pct else 0.5
                new_pan = -val
            elif "right" in p_lower:
                pct = re.search(r"(\d+)\s*%", p_lower)
                val = (float(pct.group(1)) / 100.0) if pct else 0.5
                new_pan = val
            elif "center" in p_lower or "middle" in p_lower:
                new_pan = 0.0

            new_pan = max(-1.0, min(1.0, round(new_pan, 2)))
            ops.append(AIOperation(
                op="set_pan",
                track_id=target_track.id,
                track_name=target_track.name,
                description=f"Pan track '{target_track.name}' to {int(new_pan*100)}%",
                params={"track_id": target_track.id, "pan": new_pan},
                current_value=f"{int(target_track.pan*100)}%",
                target_value=f"{int(new_pan*100)}%",
            ))
            return ops

        # SPLIT CLIP
        if "split" in p_lower or "cut" in p_lower:
            time_match = re.search(r"(\d+(?:\.\d+)?)\s*(?:s|sec|seconds)", p_lower)
            split_time = float(time_match.group(1)) if time_match else 4.0
            
            found_clip = None
            found_track = None
            for t in tracks:
                for c in t.clips:
                    if c.start_time <= split_time <= c.start_time + c.duration:
                        found_clip = c
                        found_track = t
                        break
                if found_clip:
                    break

            if found_clip and found_track:
                ops.append(AIOperation(
                    op="split_clip",
                    track_id=found_track.id,
                    track_name=found_track.name,
                    clip_id=found_clip.id,
                    description=f"Split clip '{found_clip.name}' at {split_time:0.2f}s",
                    params={"track_id": found_track.id, "clip_id": found_clip.id, "split_time": split_time},
                    current_value=f"{found_clip.duration:0.2f}s clip",
                    target_value=f"2 clips split at {split_time:0.2f}s",
                ))
            return ops

        return []

    @classmethod
    def parse_plan(cls, prompt: str, project: Project) -> AIOperationPlan:
        """Parse natural language command against project context into validated AIOperationPlan."""
        prompt_clean = prompt.strip()
        p_lower = prompt_clean.lower()
        operations: List[AIOperation] = []

        # Split into sub-clauses on conjunctions
        clauses = re.split(r"\s*(?:and|then|\+)\s*", p_lower)

        for clause in clauses:
            clause_ops = cls._parse_single_clause(clause, project)
            operations.extend(clause_ops)

        # Fallback if no operations were resolved
        if not operations:
            summary = (
                f"I parsed your prompt: \"{prompt_clean}\". "
                "Try instructions like 'Lower drums by 3dB', 'Add reverb to vocals', 'Mute track 1', 'Set tempo to 125 BPM', or 'Enable 8D audio'."
            )
            return AIOperationPlan(
                prompt=prompt_clean,
                summary=summary,
                confidence=0.3,
                operations=[],
            )

        summary_parts = [op.description for op in operations]
        summary = f"AI proposes {len(operations)} change{'s' if len(operations) > 1 else ''}: " + "; ".join(summary_parts) + "."

        return AIOperationPlan(
            prompt=prompt_clean,
            summary=summary,
            confidence=0.95,
            operations=operations,
        )
